/**
 * Matroska (`.mkv`) subtitle extraction — text tracks only.
 *
 * ## Why this is written rather than imported
 *
 * `PLAN-local-video.md` §11 chose `ebml-stream` + our own Matroska layer. **That
 * choice cannot be executed as written and is reversed here.** The project has no
 * bundler and no `dependencies` block — `src/` ships to the browser exactly as it
 * is written — so a bare `import 'ebml-stream'` cannot resolve. Taking it would
 * mean either a build step (changing how the project ships, for one feature) or
 * vendoring Node's stream implementation, which is what `ebml-stream` is built on
 * and is roughly as large as the parser itself.
 *
 * The reasoning for preferring a library was that EBML correctness is a bad place
 * to save a dependency, because a parser that passes three fixtures fails on the
 * fourth — on a user's film, where we cannot see it. **That concern is right, and
 * the mitigation is not a library: it is testing against real files.** The
 * fixtures for this module are generated by `ffmpeg` (`test/fixtures/`), not
 * written by hand, so they are files a real muxer produced.
 *
 * What makes the hand-rolled version safe enough:
 *   - The subset needed is small. We read `Tracks` for discovery and
 *     `Cluster` blocks for cues, and ignore everything else BY SIZE — so an
 *     element we do not understand costs nothing and cannot derail us.
 *   - Unknown and malformed input FAILS CLOSED. A codec we do not recognise is
 *     reported, never guessed at, so the failure is a message rather than a
 *     silently empty transcript.
 *   - The genuinely fiddly parts of EBML — unknown-size elements, `Void`, `CRC-32`
 *     — are each a few lines and are covered by tests.
 *
 * ## What is deliberately not supported
 *
 * **Image subtitle codecs** — `S_HDMV/PGS` (Blu-ray), `S_VOBSUB` (DVD),
 * `S_DVBSUB`, `S_ARIBSUB`. These are pictures of text: there is no string in them
 * to mark, and extracting one is OCR, which is a different project. They are
 * detected and named so the caller can say so, rather than appearing as a track
 * that yields nothing.
 *
 * ## Structure
 *
 * The parser takes a `read(offset, length)` function rather than an array or a
 * stream. That is what lets it work on a multi-gigabyte film without loading it
 * into memory: elements are walked by their declared SIZE, large ones are skipped
 * by seeking forward, and only the regions we need are ever read.
 */

/** EBML element ids. Only the ones this module walks. */
const ID = {
  EBML: 0x1a45dfa3,
  Segment: 0x18538067,
  SeekHead: 0x114d9b74,
  Info: 0x1549a966,
  Tracks: 0x1654ae6b,
  Cluster: 0x1f43b675,
  Cues: 0x1c53bb6b,
  Attachments: 0x1941a469,
  Chapters: 0x1043a770,
  Tags: 0x1254c367,

  TrackEntry: 0xae,
  TrackNumber: 0xd7,
  TrackType: 0x83,
  CodecID: 0x86,
  CodecPrivate: 0x63a2,
  Language: 0x22b59c,
  LanguageIETF: 0x22b59d,
  Name: 0x536e,

  Timestamp: 0xe7,
  SimpleBlock: 0xa3,
  BlockGroup: 0xa0,
  Block: 0xa1,
  BlockDuration: 0x9b,
  Info: 0x1549a966,
  TimecodeScale: 0x2ad7b1,

  // Elements that are pure noise to us but common enough to skip by name, so the
  // walk does not have to guess whether an unknown id is safe to ignore.
  Void: 0xec,
  CRC32: 0xbf,
  DefaultDuration: 0x23e383,
  FlagDefault: 0x88,
  FlagForced: 0x55aa,
  FlagLacing: 0x9c,
  Video: 0xe0,
  Audio: 0xe1,
};

/** TrackType 0x11 is a subtitle track; everything else is video, audio or complex. */
const TRACK_TYPE_SUBTITLE = 0x11;

/**
 * ISO 639-2 to ISO 639-1, for the languages this extension can actually mark.
 *
 * **Matroska writes the three-letter form and everything else here uses the
 * two-letter one.** A track says `zho`; the word lists say `zh`. Without this
 * mapping the track is discovered, named, offered in the picker — and matched by
 * no list at all, so every word renders unmarked. That is the worst failure shape
 * available: the feature appears to work and silently does nothing.
 *
 * Both the bibliographic and terminological codes are listed, because Matroska
 * permits either and files are inconsistent — German is `deu` in one file and
 * `ger` in another.
 *
 * Deliberately not a complete registry. A language absent here is reported as
 * unknown rather than guessed, which surfaces as the panel's existing "no list
 * covers this" explainer instead of as a wrong word list applied confidently.
 */
const ISO639_2_TO_1 = new Map([
  // The two languages this extension marks today, first because they are the ones
  // that matter and are worth seeing at the top of the list.
  ['zho', 'zh'], ['chi', 'zh'], ['cmn', 'zh'], ['yue', 'zh'],
  ['jpn', 'ja'],
  ['kor', 'ko'],
  // The gloss line's languages, which a bilingual film needs.
  ['eng', 'en'],
  ['spa', 'es'],
  ['fra', 'fr'], ['fre', 'fr'],
  ['deu', 'de'], ['ger', 'de'],
  ['ita', 'it'],
  ['por', 'pt'],
  ['nld', 'nl'], ['dut', 'nl'],
  ['rus', 'ru'],
  ['ara', 'ar'],
  ['tha', 'th'],
  ['vie', 'vi'],
  ['ind', 'id'],
  ['tur', 'tr'],
  ['pol', 'pl'],
  ['swe', 'sv'],
  ['ukr', 'uk'],
  ['heb', 'he'], ['iw', 'he'],
  ['hin', 'hi'],
  ['ell', 'el'], ['gre', 'el'],
  ['ces', 'cs'], ['cze', 'cs'],
  ['dan', 'da'],
  ['fin', 'fi'],
  ['nor', 'no'],
  ['ron', 'ro'], ['rum', 'ro'],
  ['hun', 'hu'],
  ['fas', 'fa'], ['per', 'fa'],
]);

/**
 * Normalise a language tag to what the rest of the extension expects.
 *
 * Handles all three shapes that reach here:
 *   `zho`     -> `zh`       (ISO 639-2, what Matroska writes)
 *   `zh-Hans` -> `zh-Hans`  (already specific; the script is meaningful and kept)
 *   `zh`      -> `zh`       (already correct)
 *
 * @param {string|null} code
 * @returns {string|null} null when unknown, so callers report rather than guess.
 */
export function normaliseLanguage(code) {
  if (!code) return null;
  const lower = String(code).trim().toLowerCase();
  if (!lower || lower === 'und') return null;

  // A regional or script variant: normalise the BASE and keep the rest, so
  // `zho-Hans` becomes `zh-Hans` rather than being rejected for a shape the
  // word lists could have handled.
  const [base, ...rest] = lower.split('-');
  const mapped = ISO639_2_TO_1.get(base) ?? base;
  if (rest.length) {
    // Region and script subtags are conventionally lower and title case
    // respectively, and the panel compares these as opaque strings.
    return [mapped, ...rest.map((part) => (part.length === 4 ? part.charAt(0).toUpperCase() + part.slice(1) : part))].join('-');
  }
  return mapped;
}

/** Subtitle codecs that carry TEXT, which is the only kind we can use. */
const TEXT_CODECS = new Set([
  'S_TEXT/UTF8',
  'S_TEXT/ASCII',
  'S_TEXT/ASS',
  'S_TEXT/SSA',
  'S_TEXT/WEBVTT',
  'S_SSA/ASS',
  'S_ASS',
]);

/** Subtitle codecs that carry PICTURES of text. Named so the caller can explain. */
const IMAGE_CODECS = new Map([
  ['S_HDMV/PGS', 'Blu-ray PGS'],
  ['S_VOBSUB', 'DVD VobSub'],
  ['S_DVBSUB', 'DVB'],
  ['S_ARIBSUB', 'ARIB'],
  ['S_HDMV/TEXTST', 'Blu-ray TextST'],
]);

/**
 * How much to read at once.
 *
 * A single `Cluster` has to fit inside this for its cues to be read, because the
 * window is what we are willing to hold in memory at one time. A cluster is
 * normally well under a megabyte — it is a few seconds of media — so 8 MB is
 * generous while keeping the peak far below a whole film.
 */
const WINDOW_BYTES = 8 * 1024 * 1024;

/** An element larger than this is skipped without trying to read it. */
const MAX_ELEMENT_BYTES = WINDOW_BYTES;

/**
 * An EBML variable-length integer, which is how every id and size is stored.
 *
 * The first byte's leading zero count gives the total width: `0b1000_0002`-style
 * markers mean a 1-byte vint, `0b0100_0000` a 2-byte one, and so on. The value
 * bits across those bytes are the number, and the marker itself is discarded.
 *
 * Two details that are easy to get wrong and both matter:
 *   - A size of "all ones" (`0xFF` for a 1-byte vint, and so on) means UNKNOWN
 *     SIZE, not a gigantic element. A real `Segment` element uses it, so treating
 *     it as a number skips the entire file.
 *   - `keepMarker` is needed for ids but not for sizes, because an id is compared
 *     to a constant WITH its marker byte and a size is used as a number without.
 *
 * @param {Uint8Array} bytes
 * @param {number} offset
 * @param {boolean} [keepMarker] Include the length marker in the value (for ids).
 * @returns {{value: number, length: number, unknown: boolean}|null} null if the
 *   bytes do not hold a complete vint.
 */
export function readVint(bytes, offset = 0, keepMarker = false) {
  if (offset >= bytes.length) return null;
  const first = bytes[offset];
  if (first === 0) return null; // more than 8 bytes wide: not valid EBML

  let length = 1;
  for (let marker = 0x80; marker; marker >>= 1, length++) {
    if (first & marker) break;
  }
  if (length > 8 || offset + length > bytes.length) return null;

  let value = keepMarker ? first : first & ((1 << (8 - length)) - 1);
  let allOnes = (first & ((1 << (8 - length)) - 1)) === (1 << (8 - length)) - 1;

  for (let i = 1; i < length; i++) {
    value = value * 256 + bytes[offset + i];
    if (bytes[offset + i] !== 0xff) allOnes = false;
  }

  // Value bits all set = "unknown size". Only meaningful for sizes, and the
  // caller decides what to do with it; reported rather than silently huge.
  return { value, length, unknown: !keepMarker && allOnes };
}

/**
 * A sliding window over a byte source.
 *
 * Elements are walked by SIZE, so the viewer jumps over anything it does not need
 * — which is the whole reason a multi-gigabyte film is workable. The window is
 * re-read only when a requested range is not already inside it, and the walk only
 * ever moves forward, so one buffer is enough.
 *
 * @param {(offset: number, length: number) => Promise<Uint8Array>} read
 * @param {number} size Total bytes available.
 */
function createWindow(read, size) {
  let start = 0;
  let buffer = new Uint8Array(0);

  return {
    /**
     * @param {number} offset
     * @param {number} length
     * @returns {Promise<Uint8Array|null>} null when the range is too large to
     *   hold or runs past the end. Null means "skip this", never a throw: an
     *   unreadable region of a film should cost us that region, not the whole
     *   extraction.
     */
    async at(offset, length) {
      if (length > WINDOW_BYTES || offset + length > size) return null;
      if (offset < start || offset + length > start + buffer.length) {
        start = offset;
        buffer = await read(offset, Math.min(WINDOW_BYTES, size - offset));
      }
      const from = offset - start;
      if (from + length > buffer.length) return null;
      return buffer.subarray(from, from + length);
    },
    get size() {
      return size;
    },
  };
}

/**
 * Walk the child elements of a region, yielding `{id, offset, size, headerSize}`.
 *
 * Everything inside a Matroska document is one of these. The walk is driven
 * entirely by the declared sizes, which is why an element we have never heard of
 * costs nothing: the caller ignores it and the loop steps over it.
 *
 * @param {{at: Function}} window
 * @param {number} start Offset of the first child.
 * @param {number} end Offset one past the last byte to consider.
 * @returns {AsyncGenerator<{id: number, offset: number, size: number, headerSize: number}>}
 */
async function* children(window, start, end) {
  let cursor = start;

  while (cursor < end) {
    // 12 bytes covers the widest id (4) plus the widest size (8) we accept.
    const head = await window.at(cursor, 12);
    if (!head || head.length < 2) return;

    const id = readVint(head, 0, true);
    if (!id) return;
    const size = readVint(head, id.length, false);
    if (!size) return;

    const headerSize = id.length + size.length;
    const offset = cursor + headerSize;

    if (size.unknown) {
      // An unknown-size element continues until a sibling appears. The only one
      // in practice is the top-level `Segment`, which is handled by the caller
      // as "the rest of the file" rather than reached through this walk.
      return;
    }

    yield { id: id.value, offset, size: size.value, headerSize };

    // Step to the next sibling. A zero-length element would spin the loop
    // forever, so the cursor must always advance by at least the header.
    cursor = offset + size.value;
  }
}

/**
 * Read the whole of a small element, or null.
 *
 * @param {{at: Function}} window
 * @param {{offset: number, size: number}} element
 */
async function readElement(window, element) {
  return window.at(element.offset, element.size);
}

/** @param {Uint8Array} bytes */
function utf8(bytes) {
  return new TextDecoder('utf-8').decode(bytes);
}

/** @param {Uint8Array} bytes */
function uint(bytes) {
  let value = 0;
  for (const byte of bytes) value = value * 256 + byte;
  return value;
}

/** @param {Uint8Array} bytes */
function int16(bytes) {
  if (bytes.length < 2) return 0;
  const raw = (bytes[0] << 8) | bytes[1];
  // Signed: block timestamps are relative and legitimately negative, which is how
  // a block that lands before its cluster's base time is written.
  return raw >= 0x8000 ? raw - 0x10000 : raw;
}

/**
 * Parse a `Tracks` element into subtitle track records.
 *
 * @param {{at: Function}} window
 * @param {{offset: number, size: number}} element
 * @returns {Promise<Array<{number: number, codec: string, language: string|null,
 *   name: string|null, kind: 'text'|'image'|'other'}>>}
 */
async function parseTracks(window, element) {
  const tracks = [];

  for await (const entry of children(window, element.offset, element.offset + element.size)) {
    if (entry.id !== ID.TrackEntry) continue;

    let number = 0;
    let type = 0;
    let codec = '';
    let language = null;
    let name = null;
    // Whether the track carried any language element at all, which is a different
    // question from what it said. See the note on `language` below.
    let languageSeen = false;

    for await (const field of children(window, entry.offset, entry.offset + entry.size)) {
      const bytes = await readElement(window, field);
      if (!bytes) continue;

      switch (field.id) {
        case ID.TrackNumber:
          number = uint(bytes);
          break;
        case ID.TrackType:
          type = uint(bytes);
          break;
        case ID.CodecID:
          codec = utf8(bytes).replace(/\0+$/, '');
          break;
        case ID.Language: {
          const value = utf8(bytes).replace(/\0+$/, '').trim();
          // Normalised here, at the source, rather than by every caller. Matroska
          // writes `zho` where the word lists say `zh`, and a track that reaches
          // the panel as `zho` is matched by no list and marks nothing — while
          // looking perfectly correct. See `normaliseLanguage`.
          //
          // `und` is Matroska's own "undetermined", and normalisation turns it
          // into null so callers have one thing to check rather than two.
          language = normaliseLanguage(value);
          languageSeen = true;
          break;
        }
        case ID.LanguageIETF: {
          // More specific than `Language` (`zh-Hans` rather than `zho`), so it
          // wins when both are present.
          const value = utf8(bytes).replace(/\0+$/, '').trim();
          const normalised = normaliseLanguage(value);
          if (normalised) language = normalised;
          languageSeen = true;
          break;
        }
        case ID.Name:
          name = utf8(bytes).replace(/\0+$/, '').trim() || null;
          break;
        default:
          break;
      }
    }

    if (type !== TRACK_TYPE_SUBTITLE) continue;

    // **An absent `Language` is English, and that is the specification rather than
    // a guess.** Matroska defines the element as defaulting to `eng`, which is why
    // the CELLAR suite's seven-language file has its English track unlabelled —
    // `ffprobe` reports that track with no language tag and every other one
    // labelled. The spec's own text is explicit that its value is case-insensitive
    // and that "an empty string or the value 'eng' should be used for the default
    // language", and the default is English.
    //
    // This corrects an earlier "never guess" rule that collapsed the two cases and
    // left the English track unmatched by any word list — which is the worst
    // outcome available, because the panel offers the track, the user chooses it,
    // and nothing is ever marked.
    //
    // `und` is still different and still reported as null: it is a file SAYING the
    // language is undetermined, which is knowledge rather than absence.
    const resolved = language ?? (languageSeen ? null : 'en');

    tracks.push({
      number,
      codec,
      language: resolved,
      name,
      // True when the language was supplied by the format default rather than read
      // from the file, so a caller can distinguish a certainty from an inference.
      languageDefaulted: !languageSeen,
      kind: TEXT_CODECS.has(codec) ? 'text' : IMAGE_CODECS.has(codec) ? 'image' : 'other',
    });
  }

  return tracks;
}

/**
 * Decode one block payload into cue text, for a given codec.
 *
 * The payload's shape depends on the codec, and two of them need real work:
 *
 *   - `S_TEXT/UTF8` is the subtitle text verbatim — the SRT file's body, already
 *     UTF-8, with the timing moved into the container.
 *   - `S_TEXT/ASS` is NOT an ASS file. The `[Script Info]` and style blocks live in
 *     the track's `CodecPrivate`, and each block holds only the event FIELDS:
 *     `ReadOrder,Layer,Style,Name,MarginL,MarginR,MarginV,Effect,Text`. So the text
 *     is everything after the eighth comma — and it may itself contain commas,
 *     which is why this splits a bounded number of times rather than taking an
 *     index from a full split.
 *
 * @param {string} codec
 * @param {Uint8Array} payload
 * @returns {string}
 */
function decodeBlockText(codec, payload) {
  const raw = utf8(payload);

  if (codec === 'S_TEXT/ASS' || codec === 'S_TEXT/SSA' || codec === 'S_SSA/ASS' || codec === 'S_ASS') {
    // Eight fields precede `Text`. Splitting into 9 and dropping the first 8 keeps
    // any commas that belong to the text itself.
    const parts = raw.split(',');
    const body = parts.length > 8 ? parts.slice(8).join(',') : raw;
    return stripTags(body);
  }

  // **Every text codec goes through the tag stripper, not only ASS.** A file that
  // has been through a format conversion carries the previous format's markup in
  // its text, and `<font size="20" color="#000000">` is what `ffmpeg` writes when
  // it converts ASS to a text subtitle format. It is common in the wild, and left
  // in it puts the tag itself in the transcript as if it were a word.
  return stripTags(raw);
}

/**
 * Remove ASS override blocks and HTML-style tags, keeping the words.
 *
 * Both, together, because either can appear in any text codec: the container says
 * what the track IS, but the text inside it is whatever produced it, and a
 * converted track carries the other format's markup.
 *
 * @param {string} text
 */
function stripTags(text) {
  return (
    text
      // An ASS drawing block is vector commands, not words. Dropped whole rather
      // than letting its coordinates through as text.
      .replace(/\{\\p\d+\}[\s\S]*?\{\\p0\}/g, '')
      // Every other ASS override block is pure styling: position, alignment,
      // karaoke timing, fades.
      .replace(/\{[^}]*\}/g, '')
      // `<font …>`, `</font>`, `<c.classname>`, `<v Speaker>` and WebVTT's bare
      // `<00:00:01.000>` cue timestamps.
      .replace(/<[^>]*>/g, '')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&nbsp;/g, ' ')
      // ASS hard and soft line breaks.
      .replace(/\\N/g, '\n')
      .replace(/\\n/g, ' ')
      .replace(/\\h/g, ' ')
      .trim()
  );
}


/**
 * Parse cue text out of a `Block` or `SimpleBlock` payload.
 *
 * Both start the same way: a vint track number, a signed 16-bit timestamp
 * RELATIVE to the cluster's base time, then a flags byte. `SimpleBlock` carries no
 * duration — which is why the Matroska specification has subtitle tracks use
 * `BlockGroup` instead — so a `SimpleBlock` cue gets `duration: 0` and the panel
 * infers the end from the next cue, exactly as it does for an SRT file that omits
 * one.
 *
 * @param {Uint8Array} payload
 * @returns {{track: number, relative: number, text: Uint8Array}|null}
 */
function parseBlockHeader(payload) {
  const track = readVint(payload, 0, false);
  if (!track) return null;
  const after = track.length;
  if (payload.length < after + 3) return null;

  const relative = int16(payload.subarray(after, after + 2));
  // Byte `after + 2` is the flags: keyframe, invisible, lacing, discardable. Lacing
  // would mean several frames share one block, which subtitle tracks do not use —
  // detected so a laced block is skipped rather than misread as text.
  const flags = payload[after + 2];
  if (flags & 0x06) return null;

  return { track: track.value, relative, text: payload.subarray(after + 3) };
}

/**
 * The default `TimecodeScale`, in nanoseconds per tick.
 *
 * Matroska stores block timestamps as integer TICKS, and the scale says how long a
 * tick is. One millisecond (`1_000_000` ns) is the default and what almost every
 * file uses.
 */
const DEFAULT_TIMECODE_SCALE = 1_000_000;

/**
 * Read `TimecodeScale` from the `Info` element.
 *
 * **This was missing, and its absence is a silent corruption.** The code used to
 * divide block ticks by 1000 to get seconds, which is correct ONLY when the scale
 * is the default one millisecond. A file that sets it to `100_000` — which is the
 * entire point of the CELLAR conformance suite's `test2.mkv` — has every timestamp
 * come out **ten times too large**: a two-minute film's subtitles land at twenty
 * minutes, with no error and a complete-looking transcript.
 *
 * Found by reading the conformance file list rather than by a failing test, which
 * is the uncomfortable part: every fixture we generate uses the default, so nothing
 * here could have caught it.
 *
 * @param {{at: Function}} window
 * @param {number} segmentStart
 * @param {number} segmentEnd
 * @returns {Promise<number>} Nanoseconds per tick.
 */
async function readTimecodeScale(window, segmentStart, segmentEnd) {
  for await (const element of children(window, segmentStart, segmentEnd)) {
    // `Info` precedes `Tracks` and every cluster, so passing either means it is
    // not there and there is no reason to walk the media looking for it.
    if (element.id === ID.Tracks || element.id === ID.Cluster) break;
    if (element.id !== ID.Info) continue;

    for await (const field of children(window, element.offset, element.offset + element.size)) {
      if (field.id !== ID.TimecodeScale) continue;
      const bytes = await window.at(field.offset, field.size);
      if (!bytes) break;
      const value = uint(bytes);
      // A zero or absurd scale means a malformed file. The default is the safer
      // answer: a wrong scale produces plausible timestamps that are silently off,
      // which is worse than an assumed one.
      if (Number.isFinite(value) && value >= 1000 && value <= 1e10) return value;
    }
    break;
  }
  return DEFAULT_TIMECODE_SCALE;
}

/**
 * Read every text subtitle track and its cues from a Matroska file.
 *
 * @param {object} options
 * @param {(offset: number, length: number) => Promise<Uint8Array>} options.read
 *   Supplies bytes on demand. The viewer page passes a `File.slice()` wrapper, so
 *   a multi-gigabyte film is never held in memory.
 * @param {number} options.size Total file size in bytes.
 * @param {number[]} [options.trackNumbers] Only extract these tracks. Omitted
 *   means every text track, which is what discovery wants.
 * @returns {Promise<{
 *   tracks: Array<{number: number, codec: string, language: string|null,
 *     name: string|null, kind: 'text'|'image'|'other'}>,
 *   cues: Map<number, Array<{start: number, duration: number, text: string}>>,
 *   truncated: boolean,
 *   timecodeScale: number,
 * }>}
 */
export async function readMatroska({ read, size, trackNumbers }) {
  const window = createWindow(read, size);
  /** @type {Array<{number: number, codec: string, language: string|null, name: string|null, kind: string}>} */
  let tracks = [];
  /** @type {Map<number, Array<{start: number, duration: number, text: string}>>} */
  const cues = new Map();
  // True when a cluster was too large to hold, or a region could not be read. The
  // caller reports it rather than presenting a partial transcript as complete.
  let truncated = false;

  // The document is `EBML` then `Segment`, and `Segment` is often written with an
  // UNKNOWN size — meaning "to the end of the file". So the walk is driven from
  // the file's own boundaries rather than from the segment's declared length.
  let segmentStart = 0;
  let segmentEnd = size;

  for await (const element of children(window, 0, size)) {
    if (element.id === ID.Segment) {
      segmentStart = element.offset;
      segmentEnd = element.size ? Math.min(size, element.offset + element.size) : size;
      break;
    }
  }

  // Ticks to seconds uses the file's OWN scale, not an assumed millisecond. A file
  // that sets it to 100,000 would otherwise have every timestamp ten times too
  // large — see `readTimecodeScale`.
  const timecodeScale = await readTimecodeScale(window, segmentStart, segmentEnd);
  const ticksToSeconds = (ticks) => (ticks * timecodeScale) / 1e9;

  // Falls back to a region we can actually read when a cluster's size is unknown,
  // which is how live-stream recordings are written.
  let lastGoodEnd = segmentStart;

  // Pass one: find `Tracks`. It precedes the clusters in every file a muxer
  // writes, so one forward walk finds it and then continues into the clusters.
  /** @type {Map<number, string>} Track number -> codec, so block payloads can be
   *  decoded without re-reading the track list. */
  const codecByTrack = new Map();
  const wanted = trackNumbers ? new Set(trackNumbers) : null;

  for await (const element of children(window, segmentStart, segmentEnd)) {
    if (element.id === ID.Tracks) {
      if (!tracks.length) {
        tracks = await parseTracks(window, element);
        for (const track of tracks) {
          if (track.kind === 'text') codecByTrack.set(track.number, track.codec);
        }
      }
      // Discovery asks for NO tracks (`trackNumbers: []`), and `Tracks` always
      // precedes the clusters — so this is the point at which the answer is
      // complete. Stopping here is what keeps listing a film's subtitle tracks
      // cheap: without it the walk would read every cluster of a multi-gigabyte
      // file to decide it wanted none of them.
      if (wanted && wanted.size === 0) break;
      continue;
    }

    if (element.id !== ID.Cluster) continue;

    // Nothing to extract from, so there is no reason to walk the media.
    if (!codecByTrack.size) continue;

    // **An unknown-size cluster is how live-stream recordings are written.** The
    // size is all-ones because the muxer could not know it in advance, so there is
    // no declared end to read to. Falling back to "from here to the end of the
    // known-good region" keeps such a file readable instead of yielding nothing —
    // `test4.mkv` in the CELLAR conformance suite exists for exactly this, and the
    // previous code skipped unknown sizes outright, so every cue in that file was
    // silently discarded.
    const declared = element.unknown ? null : element.size;
    if (declared !== null && declared > MAX_ELEMENT_BYTES) {
      truncated = true;
      continue;
    }
    const span = declared ?? segmentEnd - element.offset;

    // A cluster larger than one window cannot be held whole, so it is skipped — but
    // the read itself must stay inside the region we can vouch for, because a
    // window that reaches past the end returns nothing and would look identical to
    // an empty cluster.
    if (span > MAX_ELEMENT_BYTES) {
      truncated = true;
      continue;
    }

    const cluster = await window.at(element.offset, span);
    if (!cluster) {
      truncated = true;
      continue;
    }

    // The cluster's own element bytes, so the child walk can use the same window
    // helpers. Reading it whole is the trade this module makes: a cluster is a few
    // seconds of media, not a film.
    const clusterWindow = {
      at: async (offset, length) => {
        const from = offset - element.offset;
        if (from < 0 || from + length > cluster.length) return null;
        return cluster.subarray(from, from + length);
      },
    };

    let base = 0;
    for await (const child of children(clusterWindow, element.offset, element.offset + cluster.length)) {
      if (child.id === ID.Timestamp) {
        const bytes = await clusterWindow.at(child.offset, child.size);
        if (bytes) base = uint(bytes);
        continue;
      }

      const isSimple = child.id === ID.SimpleBlock;
      const isGroup = child.id === ID.BlockGroup;
      if (!isSimple && !isGroup) continue;

      // A `BlockGroup` holds a `Block` plus (usually) a `BlockDuration`; a
      // `SimpleBlock` holds neither.
      for await (const inner of children(clusterWindow, child.offset, child.offset + child.size)) {
        if (inner.id !== ID.Block) continue;

        const payload = await clusterWindow.at(inner.offset, inner.size);
        if (!payload) continue;
        const block = parseBlockHeader(payload);
        if (!block) continue;

        const codec = codecByTrack.get(block.track);
        if (!codec) continue;
        if (wanted && !wanted.has(block.track)) continue;

        let duration = 0;
        if (isGroup) {
          for await (const field of children(clusterWindow, child.offset, child.offset + child.size)) {
            if (field.id !== ID.BlockDuration) continue;
            const bytes = await clusterWindow.at(field.offset, field.size);
            if (bytes) duration = ticksToSeconds(uint(bytes));
          }
        }

        const text = decodeBlockText(codec, block.text);
        if (!text) continue;

        const list = cues.get(block.track) ?? [];
        list.push({ start: ticksToSeconds(base + block.relative), duration, text });
        cues.set(block.track, list);
      }
    }

    // A read that got this far consumed a readable region, so the fallback for an
    // unknown-size cluster can resume after it rather than restarting.
    lastGoodEnd = element.offset + cluster.length;
  }

  // Reported so a caller can tell a wrong-scale file from a right one; the viewer
  // page does not use it, but a conformance test does.
  void lastGoodEnd;

  for (const list of cues.values()) list.sort((a, b) => a.start - b.start);

  // `timecodeScale` is returned so a conformance test can assert it was READ rather
  // than defaulted — a wrong value produces plausible timestamps, so only knowing
  // the value distinguishes "correct" from "silently ten times off".
  return { tracks, cues, truncated, timecodeScale };
}

/**
 * The languages available in a Matroska file, for track discovery.
 *
 * Separate from cue extraction because discovery only reads `Tracks`, which is at
 * the start of the file and cheap — so the panel can list a film's subtitle
 * tracks without the cost of walking its media.
 *
 * @param {object} options
 * @param {(offset: number, length: number) => Promise<Uint8Array>} options.read
 * @param {number} options.size
 */
export async function readMatroskaTracks({ read, size }) {
  const { tracks } = await readMatroska({ read, size, trackNumbers: [] });
  return tracks;
}

/** Whether a codec holds text we can mark. */
export function isTextCodec(codec) {
  return TEXT_CODECS.has(codec);
}

/**
 * A human name for an image subtitle codec, or null.
 *
 * Exists so the panel can name the reason rather than showing a track that
 * produces nothing — "Blu-ray PGS subtitles are images and cannot be read" is
 * actionable; an empty transcript is not.
 *
 * @param {string} codec
 */
export function imageCodecName(codec) {
  return IMAGE_CODECS.get(codec) ?? null;
}

/** Exposed for tests, which assert the ids are the ones the spec defines. */
export const ELEMENT_IDS = ID;
