/**
 * Bundle `mediabunny` into `src/vendor/` for the extension to ship.
 *
 *   node tools/build-vendor.mjs
 *
 * ## Why this exists
 *
 * This project has no build step, deliberately: `src/` is copied into the release ZIP
 * as-is. `mediabunny` breaks that, because `chrome-extension://` cannot resolve a bare
 * specifier and the extension cannot load a 1.4 MB unminified bundle either.
 *
 * So this produces ONE self-contained ESM file. It is committed, because the release
 * cannot depend on `node_modules` — the ZIP is built from `src/` and nothing else, and
 * a build step that runs only on the maintainer's machine would make the published
 * extension depend on a file no test could reproduce.
 *
 * Committing generated code is a real cost, and it is the smaller one here: the
 * alternative is a toolchain every contributor needs before they can package.
 *
 * ## Tree-shaking
 *
 * `esbuild` bundles, and because mediabunny is written as ES modules with no side
 * effects, the code for formats we do not name is dropped.
 *
 * **Naming `ALL_FORMATS` is what defeats that**, and it is the obvious thing to write:
 * it is an array of every input format, so referencing it keeps every demuxer — HLS,
 * MPEG-TS, FLAC, Ogg, WAV, ADTS. Naming `MATROSKA` and `MP4` individually drops the
 * rest. Measured: 557 KB with `ALL_FORMATS`, 463 KB without.
 *
 * What we need is narrow — read a container, copy packets, write another container. No
 * encoding, no HLS, no encryption. The measurement printed below is the point: if it
 * is not much smaller than the full bundle, that is worth knowing now rather than
 * after the licence review.
 */

import { build } from 'esbuild';
import { mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'src', 'vendor');
const OUT = join(OUT_DIR, 'mediabunny.js');

mkdirSync(OUT_DIR, { recursive: true });

/**
 * The entry point, written to disk rather than passed as a string.
 *
 * Naming the exports explicitly IS the tree-shaking instruction: esbuild can only drop
 * what it can see is unused, and a bare `export *` would pull the whole library in.
 */
const ENTRY = join(OUT_DIR, '.entry.mjs');
writeFileSync(
  ENTRY,
  [
    '// Generated by tools/build-vendor.mjs — the tree-shaking entry point.',
    '// Every name here is one the reader actually uses, which is what lets esbuild',
    '// drop the rest of the library.',
    'export {',
    '  Input,',
    '  Output,',
    '  Conversion,',
    '  BufferTarget,',
    '  BlobSource,',
    '  MATROSKA,',
    '  MP4,',
    '  Mp4OutputFormat,',
    "} from 'mediabunny';",
    '',
  ].join('\n'),
);

const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2021',
  minify: true,
  legalComments: 'inline',
  outfile: OUT,
  metafile: true,
  logLevel: 'warning',
});

statSync(OUT);
const bundled = statSync(OUT).size;
const source = statSync(join(ROOT, 'node_modules', 'mediabunny', 'dist', 'bundles', 'mediabunny.min.mjs')).size;

// The winners, largest first — so the number can be interrogated rather than trusted.
const rows = Object.entries(result.metafile.outputs[OUT]?.inputs ?? {})
  .map(([name, info]) => [name.replace(/^.*node_modules\//, ''), info.bytesInOutput])
  .filter(([, bytes]) => bytes > 2000)
  .sort((a, b) => b[1] - a[1])
  .slice(0, 8);

console.log(`mediabunny.min.mjs (unbundled)  ${(source / 1024).toFixed(0)} KB`);
console.log(`src/vendor/mediabunny.js         ${(bundled / 1024).toFixed(0)} KB`);
console.log(`                                 ${((bundled / source) * 100).toFixed(0)}% of the full bundle`);
console.log('\nlargest contributors:');
for (const [name, bytes] of rows) console.log(`  ${(bytes / 1024).toFixed(0).padStart(5)} KB  ${name}`);

writeFileSync(join(OUT_DIR, 'README.md'), [
  '# `src/vendor/`',
  '',
  'Generated. Do not edit by hand — run `node tools/build-vendor.mjs`.',
  '',
  '`mediabunny.js` is a tree-shaken bundle of [mediabunny](https://mediabunny.dev)',
  '(MPL-2.0), committed because the release ZIP is built from `src/` alone and',
  'cannot depend on `node_modules`. See `THIRD-PARTY.md`.',
  '',
].join('\n'));

// The entry point is scaffolding, not a shipped file. Left behind it would be copied
// into the release ZIP and staged as if the extension needed it — and `licence.test.mjs`
// would (correctly) demand it be attributed.
rmSync(ENTRY, { force: true });

console.log('\nwrote src/vendor/mediabunny.js');
